### ISSUE TITLE
Solution upload

### ISSUE THREAD

**Issue by gorbak25** [warsztatywww/aplikacjawww#205] opened 2020-05-29 17:48 UTC
- [ ] (prev 1.) Allow participants to upload their task solutions directly to the platform.
- [ ] Upload should be editable
- [ ] Lecturers should be presented with uploaded solutions with associated upload dates
- [ ] Workshop list should include information about number of solution uploaded and (un)graded.
- [ ] (prev 2. & 3.) Users should by notified about grades and lecturers should be notified about uploads.

**Comment by krzys-h** [comment] 2020-05-29 17:52
1. :+1:, that's the biggest feature I think this platform is missing
2 & 3: Duplicate of #95

**Comment by cytadela8** [comment] 2020-12-30 17:27
I have eddited description to clearly specify what we expect from this feature and upped importance to medium

**Comment by krzys-h** [comment] 2020-12-30 18:46
Do we want just a file upload, or a textbox + attachment? The case of a textbox is more problematic because we would need features like saving drafts and math input, but may be more convenient when grading solutions (they would be displayed directly on the website instead of having to download them).

One attachment, or multiple? If we don't have a textbox, it would make a lot of sense to upload an answer document and code as separate things. If we do, I think we can get away with having the user .zip all of the remaining files on their own.

Do we need any mechanizm to disable solution uploads? They can get auto disabled after the solution is graded, or we can start hard enforcing the solution deadline (or both). If we do start enforcing the deadline, do we start enforcing the grading deadline too?

When the solution is updated, do we need to have edit history? If so, who should be able to see it - admins only, or lecturers + author too?

Should we allow setting grades if the solution was not uploaded (e.g. was sent by email instead)? I would lean towards no - if we are introducing a centralized system for solutions, the solutions should be in the system (to allow things like checking them by organizers in case of plagiarism or something)

**Comment by cytadela8** [comment] 2021-01-03 19:33
> Do we want just a file upload, or a textbox + attachment? The case of a textbox is more problematic because we would need features like saving drafts and math input, but may be more convenient when grading solutions (they would be displayed directly on the website instead of having to download them).

Tough question. If you would allow textbox input then some lecturers may ask for PDF download... I would rather stick to just file upload.

> One attachment, or multiple? If we don't have a textbox, it would make a lot of sense to upload an answer document and code as separate things. If we do, I think we can get away with having the user .zip all of the remaining files on their own.

I think we should allow multiple files. I think this will be better then asking users to zip things

> Do we need any mechanizm to disable solution uploads? They can get auto disabled after the solution is graded, or we can start hard enforcing the solution deadline (or both). If we do start enforcing the deadline, do we start enforcing the grading deadline too?

No, but show the upload time to lecturer.

> When the solution is updated, do we need to have edit history? If so, who should be able to see it - admins only, or lecturers + author too?

No textbox so no edit history. However I would consider keeping deleted files for some time for audit and recovery purposes. Maybe we should not allow to delete files even?

> Should we allow setting grades if the solution was not uploaded (e.g. was sent by email instead)? I would lean towards no - if we are introducing a centralized system for solutions, the solutions should be in the system (to allow things like checking them by organizers in case of plagiarism or something)

I think we can block setting grades when the solution was not uploaded. This is a good way to force people to use our system. We can always unlock things

**Comment by krzys-h** [comment] 2021-01-03 19:39
>> When the solution is updated, do we need to have edit history? If so, who should be able to see it - admins only, or lecturers + author too?
>
> No textbox so no edit history. However I would consider keeping deleted files for some time for audit and recovery purposes. Maybe we should not allow to delete files even?

Uploaded file change history is still edit history - this is exactly what I was talking about

**Closed** 2021-02-24 23:00 UTC
Labels: imp-medium, size-medium
